/*
 * global_meta_server.cpp
 *
 * RPC server for the GlobalMetaManagement interface (skills.md §5.12).
 *
 * Dispatch functions are generated by rpcgen from global_meta.x.
 * This file supplies the _svc bodies that rpcgen leaves empty.
 *
 * Build (after rpcgen -N global_meta.x):
 *   g++ -std=c++17 -Wall -O2 -I/usr/include/tirpc \
 *       global_meta_svc.o global_meta_xdr.o \
 *       global_meta_management.o global_meta_server.o \
 *       -o gmm_server -ltirpc -lpthread
 */

#include "global_meta_management.h"

#include <cstdio>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <string>

namespace {

GlobalMetaManagement g_gmm;

// Returns current wall-clock time as "HH:MM:SS".
std::string ts() {
    const std::time_t now = std::time(nullptr);
    const std::tm *tm_now = std::localtime(&now);
    if (tm_now == nullptr) return "??:??:??";
    std::ostringstream oss;
    oss << std::put_time(tm_now, "%H:%M:%S");
    return oss.str();
}

}  // namespace

__attribute__((constructor))
static void server_init() {
    std::printf("[GMM Server] GlobalMetaManagement RPC 启动 (prog=0x20001235)\n");
    std::printf("[GMM Server] 支持操作: register / query / remove / update / query_block\n\n");
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 1: gmm_register_1_svc
 * ══════════════════════════════════════════════════════════════════ */
gmm_status_result *
gmm_register_1_svc(gmm_register_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.register_(argp.token_key, argp.block_key,
                                           argp.token_ip,  argp.block_ip);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] REGISTER token_key=%-36s block_key=%-36s"
                " token_ip=%-16s block_ip=%-16s -> %s\n",
                t.c_str(), argp.token_key, argp.block_key,
                argp.token_ip, argp.block_ip,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 2: gmm_query_1_svc
 * ══════════════════════════════════════════════════════════════════ */
gmm_query_result *
gmm_query_1_svc(gmm_query_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_query_result res;
    static std::string token_ip_str;
    static std::string block_ip_str;
    const std::string t = ts();

    const Result<IpPair> result = g_gmm.query(argp.key);
    if (result.ok()) {
        res.found = 1;
        token_ip_str = result.value.token_ip;
        block_ip_str = result.value.block_ip;
        res.gmm_query_result_u.ips.token_ip = const_cast<char *>(token_ip_str.c_str());
        res.gmm_query_result_u.ips.block_ip = const_cast<char *>(block_ip_str.c_str());
        std::printf("[%s] QUERY        token_key=%-36s -> token_ip=%-16s block_ip=%s\n",
                    t.c_str(), argp.key, token_ip_str.c_str(), block_ip_str.c_str());
    } else {
        res.found = 0;
        std::printf("[%s] QUERY        token_key=%-36s -> %s\n",
                    t.c_str(), argp.key, result.status.message().c_str());
    }
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 3: gmm_remove_1_svc
 * ══════════════════════════════════════════════════════════════════ */
gmm_status_result *
gmm_remove_1_svc(gmm_remove_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.remove(argp.key);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] REMOVE       token_key=%-36s -> %s\n",
                t.c_str(), argp.key,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 4: gmm_update_1_svc
 * ══════════════════════════════════════════════════════════════════ */
gmm_status_result *
gmm_update_1_svc(gmm_update_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.update(argp.key, argp.new_token_ip, argp.new_block_ip);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] UPDATE       token_key=%-36s new_token_ip=%-16s new_block_ip=%-16s -> %s\n",
                t.c_str(), argp.key, argp.new_token_ip, argp.new_block_ip,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 5: gmm_query_block_1_svc
 * ══════════════════════════════════════════════════════════════════ */
gmm_query_result *
gmm_query_block_1_svc(gmm_query_block_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_query_result res;
    static std::string token_ip_str;
    static std::string block_ip_str;
    const std::string t = ts();

    const Result<IpPair> result = g_gmm.query_block(argp.key);
    if (result.ok()) {
        res.found = 1;
        token_ip_str = result.value.token_ip;
        block_ip_str = result.value.block_ip;
        res.gmm_query_result_u.ips.token_ip = const_cast<char *>(token_ip_str.c_str());
        res.gmm_query_result_u.ips.block_ip = const_cast<char *>(block_ip_str.c_str());
        std::printf("[%s] QUERY_BLOCK  block_key=%-36s -> token_ip=%-16s block_ip=%s\n",
                    t.c_str(), argp.key, token_ip_str.c_str(), block_ip_str.c_str());
    } else {
        res.found = 0;
        std::printf("[%s] QUERY_BLOCK  block_key=%-36s -> %s\n",
                    t.c_str(), argp.key, result.status.message().c_str());
    }
    return &res;
}
