/*
 * global_meta_server.cpp
 *
 * RPC server for the GlobalMetaManagement interface.
 *
 * Dispatch functions are generated by rpcgen from global_meta.x.
 * This file supplies the _svc bodies that rpcgen leaves empty.
 *
 * Build (after rpcgen -N global_meta.x):
 *   g++ -std=c++17 -Wall -O2 -I/usr/include/tirpc \
 *       global_meta_svc.o global_meta_xdr.o \
 *       global_meta_management.o global_meta_server.o \
 *       -o gmm_server -ltirpc -lpthread
 */

extern "C" {
#include "global_meta.h"
}

#include "global_meta_management.h"

#include <cstdio>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <string>

namespace {

GlobalMetaManagement g_gmm;

// Returns current wall-clock time as "HH:MM:SS".
std::string ts() {
    const std::time_t now = std::time(nullptr);
    const std::tm *tm_now = std::localtime(&now);
    if (tm_now == nullptr) return "??:??:??";
    std::ostringstream oss;
    oss << std::put_time(tm_now, "%H:%M:%S");
    return oss.str();
}

}  // namespace

__attribute__((constructor))
static void server_init() {
    std::printf("[GMM Server] GlobalMetaManagement RPC 启动 (prog=0x20001235)\n");
    std::printf("[GMM Server] 支持操作: insert / query / update / remove\n\n");
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 1: gmm_insert_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_insert_1_svc(gmm_kv_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.batchInsertGlobal({argp.key}, {argp.value})[0];
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] INSERT  key=%-36s value=%-36s -> %s\n",
                t.c_str(), argp.key, argp.value,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 2: gmm_query_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_query_result *
gmm_query_1_svc(gmm_key_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_query_result res;
    static std::string value_str;
    const std::string t = ts();

    const Result<std::string> result = g_gmm.batchQueryGlobal({argp.key})[0];
    if (result.ok()) {
        res.found = 1;
        value_str = result.value;
        res.gmm_query_result_u.value = const_cast<char *>(value_str.c_str());
        std::printf("[%s] QUERY   key=%-36s -> %s\n",
                    t.c_str(), argp.key, value_str.c_str());
    } else {
        res.found = 0;
        std::printf("[%s] QUERY   key=%-36s -> %s\n",
                    t.c_str(), argp.key, result.status.message().c_str());
    }
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 3: gmm_update_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_update_1_svc(gmm_kv_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.batchUpdateGlobal({argp.key}, {argp.value})[0];
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] UPDATE  key=%-36s new_value=%-36s -> %s\n",
                t.c_str(), argp.key, argp.value,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 4: gmm_remove_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_remove_1_svc(gmm_key_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const Status status = g_gmm.batchDeleteGlobal({argp.key})[0];
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] REMOVE  key=%-36s -> %s\n",
                t.c_str(), argp.key,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}
