/*
 * global_meta_server.cpp
 *
 * RPC server for the GlobalMetaManagement interface.
 *
 * Dispatch functions are generated by rpcgen from global_meta.x.
 * This file supplies the _svc bodies that rpcgen leaves empty.
 *
 * Build (after rpcgen -N global_meta.x):
 *   g++ -std=c++17 -Wall -O2 -I/usr/include/tirpc \
 *       -Imodule1/module1/include -Imodule1/common \
 *       global_meta_svc.o global_meta_xdr.o \
 *       module1/common/metastore/redis_meta_store_backend.o \
 *       module1/module1/src/redis_meta_store_global_adapter.o \
 *       global_meta_server.o -o gmm_server -ltirpc -lpthread -lhiredis
 */

extern "C" {
#include "global_meta.h"
}

#include "metastore/meta_store_types.h"
#include "metastore/redis_meta_store_global_adapter.h"

#include <mutex>
#include <cstdio>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

namespace {

metastore::RedisMetaStoreGlobalAdapter g_adapter;
bool g_adapter_initialized = false;
std::mutex g_adapter_mutex;

// Returns current wall-clock time as "HH:MM:SS".
std::string ts() {
    const std::time_t now = std::time(nullptr);
    const std::tm *tm_now = std::localtime(&now);
    if (tm_now == nullptr) return "??:??:??";
    std::ostringstream oss;
    oss << std::put_time(tm_now, "%H:%M:%S");
    return oss.str();
}

metastore::MetaStoreInitOptions BuildAdapterOptions() {
    metastore::MetaStoreInitOptions options;
    options.backend = metastore::BackendKind::kRedis;
    options.endpoint = "127.0.0.1:6379";
    options.db_index = 0;
    return options;
}

metastore::Status EnsureAdapterInitializedLocked() {
    if (g_adapter_initialized) {
        return metastore::Status::OK();
    }

    const metastore::MetaStoreInitOptions options = BuildAdapterOptions();
    (void)g_adapter.reset();
    const metastore::Status init_status = g_adapter.init(options);
    if (init_status.ok()) {
        g_adapter_initialized = true;
        std::printf("[GMM Server] RedisMetaStoreGlobalAdapter init OK (%s, db=%d)\n",
                    options.endpoint.c_str(), options.db_index);
    } else {
        std::printf("[GMM Server] RedisMetaStoreGlobalAdapter init failed: %s\n",
                    init_status.message().c_str());
    }
    return init_status;
}

metastore::Status FirstStatusOrInternal(
    const std::vector<metastore::Status>& statuses, const char* op_name) {
    if (statuses.empty()) {
        return metastore::Status::Internal(std::string(op_name) +
                                           " returned no status");
    }
    return statuses.front();
}

metastore::Result<std::string> FirstResultOrInternal(
    const std::vector<metastore::Result<std::string>>& results,
    const char* op_name) {
    if (results.empty()) {
        return {metastore::Status::Internal(std::string(op_name) +
                                            " returned no result"),
                ""};
    }
    return results.front();
}

metastore::Status InsertOneGlobal(const std::string& key,
                                  const std::string& value) {
    const std::lock_guard<std::mutex> guard(g_adapter_mutex);
    const metastore::Status init_status = EnsureAdapterInitializedLocked();
    if (!init_status.ok()) {
        return init_status;
    }
    return FirstStatusOrInternal(g_adapter.batchInsertGlobal({key}, {value}),
                                 "batchInsertGlobal");
}

metastore::Result<std::string> QueryOneGlobal(const std::string& key) {
    const std::lock_guard<std::mutex> guard(g_adapter_mutex);
    const metastore::Status init_status = EnsureAdapterInitializedLocked();
    if (!init_status.ok()) {
        return {init_status, ""};
    }
    return FirstResultOrInternal(g_adapter.batchQueryGlobal({key}),
                                 "batchQueryGlobal");
}

metastore::Status UpdateOneGlobal(const std::string& key,
                                  const std::string& value) {
    const std::lock_guard<std::mutex> guard(g_adapter_mutex);
    const metastore::Status init_status = EnsureAdapterInitializedLocked();
    if (!init_status.ok()) {
        return init_status;
    }
    return FirstStatusOrInternal(g_adapter.batchUpdateGlobal({key}, {value}),
                                 "batchUpdateGlobal");
}

metastore::Status DeleteOneGlobal(const std::string& key) {
    const std::lock_guard<std::mutex> guard(g_adapter_mutex);
    const metastore::Status init_status = EnsureAdapterInitializedLocked();
    if (!init_status.ok()) {
        return init_status;
    }

    const metastore::Result<std::string> existing =
        FirstResultOrInternal(g_adapter.batchQueryGlobal({key}),
                              "batchQueryGlobal");
    if (!existing.ok()) {
        return existing.status;
    }

    return FirstStatusOrInternal(g_adapter.batchDeleteGlobal({key}),
                                 "batchDeleteGlobal");
}

}  // namespace

__attribute__((constructor))
static void server_init() {
    std::printf("[GMM Server] GlobalMetaManagement RPC 启动 (prog=0x20001235)\n");
    std::printf("[GMM Server] 支持操作: insert / query / update / remove\n\n");
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 1: gmm_insert_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_insert_1_svc(gmm_kv_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const metastore::Status status = InsertOneGlobal(argp.key, argp.value);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] INSERT  key=%-36s value=%-36s -> %s\n",
                t.c_str(), argp.key, argp.value,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 2: gmm_query_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_query_result *
gmm_query_1_svc(gmm_key_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_query_result res;
    static std::string value_str;
    const std::string t = ts();

    const metastore::Result<std::string> result = QueryOneGlobal(argp.key);
    if (result.ok()) {
        res.found = 1;
        value_str = result.value;
        res.gmm_query_result_u.value = const_cast<char *>(value_str.c_str());
        std::printf("[%s] QUERY   key=%-36s -> %s\n",
                    t.c_str(), argp.key, value_str.c_str());
    } else {
        res.found = 0;
        std::printf("[%s] QUERY   key=%-36s -> %s\n",
                    t.c_str(), argp.key, result.status.message().c_str());
    }
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 3: gmm_update_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_update_1_svc(gmm_kv_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const metastore::Status status = UpdateOneGlobal(argp.key, argp.value);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] UPDATE  key=%-36s new_value=%-36s -> %s\n",
                t.c_str(), argp.key, argp.value,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}

/* ══════════════════════════════════════════════════════════════════
 * 过程 4: gmm_remove_1_svc
 * ══════════════════════════════════════════════════════════════════ */
extern "C" gmm_status_result *
gmm_remove_1_svc(gmm_key_arg argp, [[maybe_unused]] struct svc_req *rqstp)
{
    static gmm_status_result res;
    const std::string t = ts();

    const metastore::Status status = DeleteOneGlobal(argp.key);
    res.status = status.ok() ? 0 : -1;
    std::printf("[%s] REMOVE  key=%-36s -> %s\n",
                t.c_str(), argp.key,
                status.ok() ? "OK" : status.message().c_str());
    return &res;
}
